In [1]:
import pandas as pd

In [174]:
df = pd.read_csv(r'C:\Users\pandi\Desktop\Abhiraj\Data Science\Notes\Sql Dataset\dataset_1_202603312312.csv')

In [50]:
df

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [25]:
df.columns

Index(['destination', 'passanger', 'weather', 'temperature', 'time', 'coupon',
       'expiration', 'gender', 'age', 'maritalStatus', 'has_children',
       'education', 'occupation', 'income', 'car', 'Bar', 'CoffeeHouse',
       'CarryAway', 'RestaurantLessThan20', 'Restaurant20To50',
       'toCoupon_GEQ5min', 'toCoupon_GEQ15min', 'toCoupon_GEQ25min',
       'direction_same', 'direction_opp', 'Y', 'row_count'],
      dtype='object')

In [26]:
df[['weather','temperature']]

      weather  temperature
0       Sunny           55
1       Sunny           80
2       Sunny           80
3       Sunny           80
4       Sunny           80
...       ...          ...
12679   Rainy           55
12680   Rainy           55
12681   Snowy           30
12682   Snowy           30
12683   Sunny           80

[12684 rows x 2 columns]

In [12]:
df.head(10)

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
5,No Urgent Place,Friend(s),Sunny,80,6PM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,6
6,No Urgent Place,Friend(s),Sunny,55,2PM,Carry out & Take away,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,7
7,No Urgent Place,Kid(s),Sunny,80,10AM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,8
8,No Urgent Place,Kid(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,9
9,No Urgent Place,Kid(s),Sunny,80,10AM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,10

In [27]:
df['passanger'].unique()

array(['Alone', 'Friend(s)', 'Kid(s)', 'Partner'], dtype=object)

In [33]:
df[df['destination']=='Home']

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
13,Home,Alone,Sunny,55,6PM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,1,0,1,14
14,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,15
15,Home,Alone,Sunny,80,6PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,16
35,Home,Alone,Sunny,55,6PM,Bar,1d,Male,21,Single,...,4~8,4~8,less1,1,0,0,1,0,1,36
36,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Male,21,Single,...,4~8,4~8,less1,1,1,0,0,1,0,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12675,Home,Alone,Snowy,30,10PM,Coffee House,2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,0,1,0,12676
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680

In [37]:
df.sort_values('coupon')

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
11702,Home,Partner,Sunny,30,10PM,Bar,2h,Female,50plus,Married partner,...,4~8,1~3,less1,1,1,1,0,1,0,11703
9930,No Urgent Place,Alone,Snowy,30,2PM,Bar,1d,Female,21,Single,...,gt8,gt8,4~8,1,0,0,0,1,0,9931
10632,Home,Alone,Rainy,55,6PM,Bar,1d,Male,21,Single,...,gt8,less1,less1,1,1,1,0,1,0,10633
7997,No Urgent Place,Friend(s),Rainy,55,10PM,Bar,2h,Male,26,Unmarried partner,...,4~8,never,1~3,1,1,0,0,1,1,7998
11166,Work,Alone,Snowy,30,7AM,Bar,1d,Female,41,Married partner,...,gt8,1~3,less1,1,1,1,0,1,0,11167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,Home,Alone,Sunny,80,6PM,Restaurant(<20),1d,Female,31,Unmarried partner,...,1~3,1~3,less1,1,0,0,1,0,1,10477
5447,Home,Alone,Sunny,80,10PM,Restaurant(<20),2h,Female,50plus,Single,...,less1,less1,never,1,0,0,1,0,0,5448
10478,Home,Alone,Snowy,30,10PM,Restaurant(<20),2h,Female,31,Unmarried partner,...,1~3,1~3,less1,1,1,1,0,1,0,10479
5440,No Urgent Place,Alone,Sunny,80,2PM,Restaurant(<20),2h,Female,50plus,Single,...,less1,less1,never,1,1,0,0,1,0,5441
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1

In [55]:
df.rename(columns={'destination':'dest'},inplace = True)  
#if you want to modify the column paramently apply inplace = True

In [56]:
df

,dest,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [57]:
df

,dest,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [77]:
df.groupby(['occupation']).size() # this prove the data with count 
df.groupby(['occupation']).size().to_frame('count') # to_frame-> added the count coloumn name 
df.groupby(['occupation']).size().to_frame('count').reset_index() # reset_index --> added the index value

                                   occupation  count
0                  Architecture & Engineering    175
1    Arts Design Entertainment Sports & Media    629
2   Building & Grounds Cleaning & Maintenance     44
3                        Business & Financial    544
4                 Community & Social Services    241
5                     Computer & Mathematical   1408
6                   Construction & Extraction    154
7                  Education&Training&Library    943
8                  Farming Fishing & Forestry     43
9          Food Preparation & Serving Related    298
10       Healthcare Practitioners & Technical    244
11                         Healthcare Support    242
12          Installation Maintenance & Repair    133
13                                      Legal    219
14               Life Physical Social Science    170
15                                 Management    838
16            Office & Administrative Support    639
17                    Personal Care & Service    175
18                     Production Occupations    110
19                         Protective Service    175
20                                    Retired    495
21                            Sales & Related   1093
22                                    Student   1584
23           Transportation & Material Moving    218
24                                 Unemployed   1870

In [91]:
df.groupby('weather')['temperature'].mean().to_frame('avg_temp').reset_index()

  weather   avg_temp
0   Rainy  55.000000
1   Snowy  30.000000
2   Sunny  68.946271

In [96]:
df

,dest,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [104]:
df.groupby('weather')['temperature'].count().to_frame('count').reset_index()

  weather  count
0   Rainy   1210
1   Snowy   1405
2   Sunny  10069

In [105]:
df

,dest,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [122]:
df.groupby('weather')['temperature'].nunique(['temperature']).to_frame('count_distinct_temp').reset_index()

  weather  count_distinct_temp
0   Rainy                    1
1   Snowy                    1
2   Sunny                    3

In [123]:
df

,dest,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [128]:
df.groupby('weather')['temperature'].sum().to_frame('sum_temp').reset_index()

  weather  sum_temp
0   Rainy     66550
1   Snowy     42150
2   Sunny    694220

In [131]:
df.groupby('weather')['temperature'].min().to_frame('min_temp').reset_index()

  weather  min_temp
0   Rainy        55
1   Snowy        30
2   Sunny        30

In [132]:
df.groupby('weather')['temperature'].max().to_frame('min_temp').reset_index()

  weather  min_temp
0   Rainy        55
1   Snowy        30
2   Sunny        80

In [150]:
df.groupby('occupation').filter(lambda x: x['occupation'].iloc[0] == 'Student').groupby('occupation').size()

occupation
Student    1584
dtype: int64

In [162]:
df.groupby('occupation').filter(lambda x: x['occupation'].iloc[0]=='Student').groupby('occupation').size()

occupation
Student    1584
dtype: int64

In [164]:
df.columns

Index(['dest', 'passanger', 'weather', 'temperature', 'time', 'coupon',
       'expiration', 'gender', 'age', 'maritalStatus', 'has_children',
       'education', 'occupation', 'income', 'car', 'Bar', 'CoffeeHouse',
       'CarryAway', 'RestaurantLessThan20', 'Restaurant20To50',
       'toCoupon_GEQ5min', 'toCoupon_GEQ15min', 'toCoupon_GEQ25min',
       'direction_same', 'direction_opp', 'Y', 'row_count'],
      dtype='object')

In [190]:
df1= pd.read_csv(r'C:\Users\pandi\Desktop\Abhiraj\Data Science\Notes\Sql Dataset\table_to_union_202604011758.csv')

In [167]:
df1

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,UNION,UNION,UNION,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1

In [183]:
pd.concat([df,df1])['destination'].unique()

array(['No Urgent Place', 'Home', 'Work', 'UNION'], dtype=object)

In [185]:
pd.concat([df,df1])['destination'].drop_duplicates()

0     No Urgent Place
13               Home
16               Work
0               UNION
Name: destination, dtype: object

In [191]:
df2= pd.read_csv(r'C:\Users\pandi\Desktop\Abhiraj\Data Science\Notes\Sql Dataset\table_to_join_202604011812.csv')

In [199]:
pd.merge(df,df2[['part_of_day','time']], on= 'time',how = 'inner')[['destination','time','part_of_day']]

           destination  time part_of_day
0      No Urgent Place   2PM   Afternoon
1      No Urgent Place  10AM     Morning
2      No Urgent Place  10AM     Morning
3      No Urgent Place   2PM   Afternoon
4      No Urgent Place   2PM   Afternoon
...                ...   ...         ...
12679             Home   6PM     Evening
12680             Work   7AM     Morning
12681             Work   7AM     Morning
12682             Work   7AM     Morning
12683             Work   7AM     Morning

[12684 rows x 3 columns]

In [200]:
df.columns

Index(['destination', 'passanger', 'weather', 'temperature', 'time', 'coupon',
       'expiration', 'gender', 'age', 'maritalStatus', 'has_children',
       'education', 'occupation', 'income', 'car', 'Bar', 'CoffeeHouse',
       'CarryAway', 'RestaurantLessThan20', 'Restaurant20To50',
       'toCoupon_GEQ5min', 'toCoupon_GEQ15min', 'toCoupon_GEQ25min',
       'direction_same', 'direction_opp', 'Y', 'row_count'],
      dtype='object')

In [212]:
df[df['passanger'] == 'Alone'][['destination' ,'passanger']]

           destination passanger
0      No Urgent Place     Alone
1      No Urgent Place     Alone
2      No Urgent Place     Alone
3      No Urgent Place     Alone
4      No Urgent Place     Alone
...                ...       ...
12679             Home     Alone
12680             Work     Alone
12681             Work     Alone
12682             Work     Alone
12683             Work     Alone

[12684 rows x 2 columns]

In [219]:
df[df['weather'].str.startswith('Sun')]

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Alone,Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Alone,Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Alone,Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Alone,Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12673,Home,Alone,Sunny,30,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,0,12674
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Alone,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Alone,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [228]:
df[(df['temperature'] >29) & (df['temperature'] < 75)]['temperature'].unique()

array([55, 30])

In [245]:
df[df['occupation'].isin(['Sales & Related','Management'])]['occupation']

193      Sales & Related
194      Sales & Related
195      Sales & Related
196      Sales & Related
197      Sales & Related
              ...
12679    Sales & Related
12680    Sales & Related
12681    Sales & Related
12682    Sales & Related
12683    Sales & Related
Name: occupation, Length: 1931, dtype: object